---

- name: Check blackbox exporter
  stat:
    path: /usr/sbin/blackbox_exporter
  register: blackbox_exporter_bin


- name: Download blackbox exporter
  get_url:
    url: https://github.com/prometheus/blackbox_exporter/releases/download/v0.24.0/blackbox_exporter-0.24.0.linux-amd64.tar.gz 
    dest: /tmp/blackbox_exporter-0.24.0.linux-amd64.tar.gz
  when: blackbox_exporter_bin.stat.exists != true


- name: Extract blackbox exporter
  ansible.builtin.unarchive:
    src: /tmp/blackbox_exporter-0.24.0.linux-amd64.tar.gz
    dest: /usr/sbin
    owner: root
    group: root
    mode: 0755
    remote_src: true
    exclude:
    - LICENSE
    - NOTICE
    - blackbox.yml
    extra_opts:
    - --strip-components
    - 1
  when: blackbox_exporter_bin.stat.exists != true


- name: Add user for blackbox_exporter
  user:
    name: prometheus
    create_home: no


- name: Copy env file
  template:
    src: blackbox_exporter
    dest: /etc/default/blackbox_exporter
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart blackbox exporter


- name: Copy systemd unit
  copy:
    src: blackbox_exporter.service
    dest: /etc/systemd/system/blackbox_exporter.service
    owner: root
    group: root
    mode: 0644


- name: Create blackbox exporter config dif
  file:
    state: directory
    dest: /etc/blackbox
    owner: prometheus
    group: prometheus
    mode: 0644


- name: Copy blackbox config
  copy:
    src: blackbox.yml
    dest: /etc/blackbox/blackbox.yml
    owner: prometheus
    group: prometheus
    mode: 0644

 
- name: Start blackbox exporter
  systemd:
    name: blackbox_exporter
    state: started
    daemon_reload: true
    enabled: true
